version: '3.7'
services:

  licensingservice:
    image: licenseserv:latest
    ports:
      - "8074:8074"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_CLOUD_CONFIG_URI:
        http://192.168.0.207:8071
      CONFIGSERVER_PORT: "8071"
      DATABASESERVER_PORT: "5431"
    networks:
      backend:
        aliases:
          - "licenseserv"
networks:
  backend:
    external:
      name: backendnetwork